# Generated by Django 5.1.3 on 2024-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Укажите цену в сомах')),
                ('image', models.ImageField(upload_to='drink_images/')),
                ('is_new', models.BooleanField(default=False)),
                ('size', models.DecimalField(decimal_places=2, help_text='Размер напитка в литрах (например, 0.33 для 330 мл)', max_digits=3)),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(help_text='указывайте цену в сомах')),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='pizza_images/')),
                ('is_new', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(verbose_name='вес в граммах')),
            ],
        ),
    ]
